---
require: rubocop-rails

# Ignore some folders completely
AllCops:
  NewCops: enable
  Exclude:
    - .buildkite/**/*
    - bin/**/*
    - shared/**/*
    - log/**/*
    - public/**/*
    - remote/**/*
    - tmp/**/*
    - db/schema.rb

# Yes, keep lines shorter than 80 characters.
# Yes, keep names short and succinct.
# But, no need to zealous about it.
Layout/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false

# Personally, I'd rather read status: 200 than status: :ok ¯\_(ツ)_/¯
Rails/HttpStatus:
  Enabled: false

# Forcing ASCII is restricts comments to English only. Many international teams
# write comments in their native languages (e.g. Chinese, French, ...) and are
# not helped by this rule. UTF-8 is widely supported today. Let's forget ASCII.
Style/AsciiComments:
  Enabled: false

# Forcing top-level class documentation comments seems like a good idea,
# but it's tidious and against the idea of "convention over configuration".
# For example when you read `class ProductsController` all Rails developers know
# what that is and how it works. It's conventional and baked in, no need to
# force comments on such a class.
Style/Documentation:
  Enabled: false

# Frozen string literals are default behaviour since Rails 3.
# There is no use case for this outdated cop?
Style/FrozenStringLiteralComment:
  Enabled: false

# Has been causing bugs, temporarily disabling.
Style/PercentLiteralDelimiters:
  Enabled: false

# Until today I have never needed to know created_at and updated_at. ¯\_(ツ)_/¯
# Let's only add them when we have a good reason.
Rails/CreateTableWithTimestamps:
  Enabled: false

# Because warning asked to add these...
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true


